[global]
log_level = 'info'

[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = false

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true
auto_register_counterparty_payee = false
clear_limit = 50

[mode.packets.ics20_max_memo_size]
enabled = true
size = 32768

[mode.packets.ics20_max_receiver_size]
enabled = true
size = 2048

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'spn-1'
type = 'CosmosSdk'
ccv_consumer_chain = false
rpc_addr = 'http://0.0.0.0:26657'
grpc_addr = 'http://0.0.0.0:9090'
event_source = { batch_delay = '500ms', mode = 'push', url = 'ws://localhost:26657/websocket' }
rpc_timeout = '10s'
trusted_node = false
account_prefix = 'spn'
key_name = 'steve'
address_type = { derivation = 'cosmos' }
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 400000
gas_price = { denom = 'uspn', price = 0.025 }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '14days'
trust_threshold = { denominator = '3', numerator = '1' }
memo_prefix = ''
sequential_batch_tx = false

[[chains]]
id = 'orbit-1'
type = 'CosmosSdk'
ccv_consumer_chain = false
rpc_addr = 'http://localhost:26659'
grpc_addr = 'http://localhost:9092'
event_source = { batch_delay = '500ms', mode = 'push', url = 'ws://localhost:26659/websocket' }
rpc_timeout = '10s'
trusted_node = false
account_prefix = 'spn'
key_name = 'joe'
address_type = { derivation = 'cosmos' }
key_store_type = 'Test'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 400000
gas_price = { price = 0.025, denom = 'uspn' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '14days'
trust_threshold = { denominator = '3', numerator = '1' }
memo_prefix = ''
sequential_batch_tx = false
