version: 1
build:
  proto:
    path: proto
accounts:
  - name: alice
    coins:
      - 200000000uspn
    mnemonic: slide moment original seven milk crawl help text kick fluid boring awkward doll wonder sure fragile plate grid hard next casual expire okay body
  - name: bob
    coins:
      - 200000000uspn
    mnemonic: trap possible liquid elite embody host segment fantasy swim cable digital eager tiny broom burden diary earn hen grow engine pigeon fringe claim program
  - name: carol
    coins:
      - 200000000uspn
    mnemonic: great immense still pill defense fetch pencil slow purchase symptom speed arm shoot fence have divorce cigar rapid hen vehicle pear evolve correct nerve
  - name: dave
    coins:
      - 200000000uspn
    mnemonic: resist portion leisure lawn shell lunch inhale start pupil add fault segment hour dwarf toddler insect frame math remove twist easy paddle nice rhythm
  - name: joe
    coins:
      - 200000000uspn
    mnemonic: diary behind allow lawn loop assault armor survey media toe rural mass skull way crater tobacco pair glare window soon lift pistol fitness annual
  - name: steve
    coins:
      - 200000000uspn
    mnemonic: initial aisle blush gift shuffle hat solar dove dwarf soup credit acid update seed mercy thumb swear main verb image dove rose chat inmate
  - name: olivia
    coins:
      - 200000000uspn
    mnemonic: dinosaur submit around jacket movie garden crash weather matter option time cabbage butter mind skin nature ride mosquito seat lock elephant merit empower come
faucet:
  name: bob
  coins:
    - 100000uspn
  host: 0.0.0.0:4500
genesis:
  app_state:
    bank:
      denom_metadata:
        - base: uspn
          denom_units:
            - aliases:
                - microspn
              denom: uspn
              exponent: "0"
            - aliases:
                - millispn
              denom: mspn
              exponent: "3"
            - denom: spn
              exponent: "6"
          description: The native staking token of Ignite Network
          display: spn
          name: Ignite Network
          symbol: SPN
    claim:
      airdrop_supply:
        supply:
          amount: "1000"
          denom: drop
      claim_record_list:
        - address: spn1ezptsm3npn54qx9vvpah4nymre59ykr9exx2ul
          claimable: "400"
        - address: spn1aqn8ynvr3jmq67879qulzrwhchq5dtrvtx0nhe
          claimable: "500"
        - address: spn1pkdk6m2nh77nlaep84cylmkhjder3arey7rll5
          claimable: "100"
      initial_claim:
        enabled: true
        mission_id: "0"
      mission_count: 4
      mission_list:
        - description: "initial claim"
          mission_id: "0"
          weight: "0.25"
        - description: "staking"
          mission_id: "1"
          weight: "0.25"
        - description: "voting"
          mission_id: "2"
          weight: "0.25"
        - description: "sending request"
          mission_id: "3"
          weight: "0.25"
    crisis:
      constant_fee:
        denom: uspn
    fundraising:
      params:
        auction_creation_fee:
          - amount: "100"
            denom: uspn
    gov:
      deposit_params:
        min_deposit:
          - amount: "1"
            denom: uspn
    launch:
      params:
        launch_time_range:
          min_launch_time: 5s
        revert_delay: 5s
    mint:
      params:
        distribution_proportions:
          community_pool: "0.300000000000000000"
          funded_addresses: "0.400000000000000000"
          staking: "0.300000000000000000"
        funded_addresses:
          - address: spn1ezptsm3npn54qx9vvpah4nymre59ykr9exx2ul
            weight: "0.400000000000000000"
          - address: spn1aqn8ynvr3jmq67879qulzrwhchq5dtrvtx0nhe
            weight: "0.300000000000000000"
          - address: spn1pkdk6m2nh77nlaep84cylmkhjder3arey7rll5
            weight: "0.300000000000000000"
        mint_denom: uspn
    monitoringp:
      params:
        consumer_chain_id: orbit-1
        consumer_revision_height: "1"
        consumer_unbonding_period: "2"
        last_block_height: "1"
    participation:
      params:
        allocation_price:
          bonded: "1000"
        participation_tier_list:
          - benefits:
              max_bid_amount: "1000"
            required_allocations: "1"
            tier_id: "1"
          - benefits:
              max_bid_amount: "2000"
            required_allocations: "2"
            tier_id: "2"
          - benefits:
              max_bid_amount: "10000"
            required_allocations: "5"
            tier_id: "3"
          - benefits:
              max_bid_amount: "30000"
            required_allocations: "10"
            tier_id: "4"
        registration_period: 604800s
        withdrawal_delay: 1209600s
    staking:
      params:
        bond_denom: uspn
  chain_id: spn-1
validators:
  - name: alice
    home: "$HOME/.spn"
    bonded: 100000000uspn
#client:
#  typescript:
#    path: "ignite-ui/src/generated"
