// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: network/launch/v1/chain.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Chain struct {
	LaunchId               uint64         `protobuf:"varint,1,opt,name=launch_id,json=launchId,proto3" json:"launch_id,omitempty"`
	CoordinatorId          uint64         `protobuf:"varint,2,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	GenesisChainId         string         `protobuf:"bytes,3,opt,name=genesis_chain_id,json=genesisChainId,proto3" json:"genesis_chain_id,omitempty"`
	CreatedAt              int64          `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SourceUrl              string         `protobuf:"bytes,5,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	SourceHash             string         `protobuf:"bytes,6,opt,name=source_hash,json=sourceHash,proto3" json:"source_hash,omitempty"`
	InitialGenesis         InitialGenesis `protobuf:"bytes,7,opt,name=initial_genesis,json=initialGenesis,proto3" json:"initial_genesis"`
	HasProject             bool           `protobuf:"varint,8,opt,name=has_project,json=hasProject,proto3" json:"has_project,omitempty"`
	ProjectId              uint64         `protobuf:"varint,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	IsMainnet              bool           `protobuf:"varint,10,opt,name=is_mainnet,json=isMainnet,proto3" json:"is_mainnet,omitempty"`
	LaunchTriggered        bool           `protobuf:"varint,11,opt,name=launch_triggered,json=launchTriggered,proto3" json:"launch_triggered,omitempty"`
	LaunchTime             time.Time      `protobuf:"bytes,12,opt,name=launch_time,json=launchTime,proto3,stdtime" json:"launch_time"`
	ConsumerRevisionHeight int64          `protobuf:"varint,13,opt,name=consumer_revision_height,json=consumerRevisionHeight,proto3" json:"consumer_revision_height,omitempty"`
	MonitoringConnected    bool           `protobuf:"varint,14,opt,name=monitoring_connected,json=monitoringConnected,proto3" json:"monitoring_connected,omitempty"`
	// account_balance is the balance given to approved accounts
	// for this chain.  If not set, the balances used will be those
	// contained in the requests
	AccountBalance github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,15,rep,name=account_balance,json=accountBalance,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"account_balance"`
	Metadata       []byte                                   `protobuf:"bytes,16,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (m *Chain) Reset()         { *m = Chain{} }
func (m *Chain) String() string { return proto.CompactTextString(m) }
func (*Chain) ProtoMessage()    {}
func (*Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_5649fed3e1144d90, []int{0}
}
func (m *Chain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Chain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chain.Merge(m, src)
}
func (m *Chain) XXX_Size() int {
	return m.Size()
}
func (m *Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_Chain proto.InternalMessageInfo

func (m *Chain) GetLaunchId() uint64 {
	if m != nil {
		return m.LaunchId
	}
	return 0
}

func (m *Chain) GetCoordinatorId() uint64 {
	if m != nil {
		return m.CoordinatorId
	}
	return 0
}

func (m *Chain) GetGenesisChainId() string {
	if m != nil {
		return m.GenesisChainId
	}
	return ""
}

func (m *Chain) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Chain) GetSourceUrl() string {
	if m != nil {
		return m.SourceUrl
	}
	return ""
}

func (m *Chain) GetSourceHash() string {
	if m != nil {
		return m.SourceHash
	}
	return ""
}

func (m *Chain) GetInitialGenesis() InitialGenesis {
	if m != nil {
		return m.InitialGenesis
	}
	return InitialGenesis{}
}

func (m *Chain) GetHasProject() bool {
	if m != nil {
		return m.HasProject
	}
	return false
}

func (m *Chain) GetProjectId() uint64 {
	if m != nil {
		return m.ProjectId
	}
	return 0
}

func (m *Chain) GetIsMainnet() bool {
	if m != nil {
		return m.IsMainnet
	}
	return false
}

func (m *Chain) GetLaunchTriggered() bool {
	if m != nil {
		return m.LaunchTriggered
	}
	return false
}

func (m *Chain) GetLaunchTime() time.Time {
	if m != nil {
		return m.LaunchTime
	}
	return time.Time{}
}

func (m *Chain) GetConsumerRevisionHeight() int64 {
	if m != nil {
		return m.ConsumerRevisionHeight
	}
	return 0
}

func (m *Chain) GetMonitoringConnected() bool {
	if m != nil {
		return m.MonitoringConnected
	}
	return false
}

func (m *Chain) GetAccountBalance() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.AccountBalance
	}
	return nil
}

func (m *Chain) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type InitialGenesis struct {
	// Types that are valid to be assigned to Source:
	//
	//	*InitialGenesis_DefaultInitialGenesis
	//	*InitialGenesis_GenesisUrl
	//	*InitialGenesis_GenesisConfig
	Source isInitialGenesis_Source `protobuf_oneof:"source"`
}

func (m *InitialGenesis) Reset()         { *m = InitialGenesis{} }
func (m *InitialGenesis) String() string { return proto.CompactTextString(m) }
func (*InitialGenesis) ProtoMessage()    {}
func (*InitialGenesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_5649fed3e1144d90, []int{1}
}
func (m *InitialGenesis) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InitialGenesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InitialGenesis.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InitialGenesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitialGenesis.Merge(m, src)
}
func (m *InitialGenesis) XXX_Size() int {
	return m.Size()
}
func (m *InitialGenesis) XXX_DiscardUnknown() {
	xxx_messageInfo_InitialGenesis.DiscardUnknown(m)
}

var xxx_messageInfo_InitialGenesis proto.InternalMessageInfo

type isInitialGenesis_Source interface {
	isInitialGenesis_Source()
	MarshalTo([]byte) (int, error)
	Size() int
}

type InitialGenesis_DefaultInitialGenesis struct {
	DefaultInitialGenesis *DefaultInitialGenesis `protobuf:"bytes,1,opt,name=default_initial_genesis,json=defaultInitialGenesis,proto3,oneof" json:"default_initial_genesis,omitempty"`
}
type InitialGenesis_GenesisUrl struct {
	GenesisUrl *GenesisURL `protobuf:"bytes,2,opt,name=genesis_url,json=genesisUrl,proto3,oneof" json:"genesis_url,omitempty"`
}
type InitialGenesis_GenesisConfig struct {
	GenesisConfig *GenesisConfig `protobuf:"bytes,3,opt,name=genesis_config,json=genesisConfig,proto3,oneof" json:"genesis_config,omitempty"`
}

func (*InitialGenesis_DefaultInitialGenesis) isInitialGenesis_Source() {}
func (*InitialGenesis_GenesisUrl) isInitialGenesis_Source()            {}
func (*InitialGenesis_GenesisConfig) isInitialGenesis_Source()         {}

func (m *InitialGenesis) GetSource() isInitialGenesis_Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *InitialGenesis) GetDefaultInitialGenesis() *DefaultInitialGenesis {
	if x, ok := m.GetSource().(*InitialGenesis_DefaultInitialGenesis); ok {
		return x.DefaultInitialGenesis
	}
	return nil
}

func (m *InitialGenesis) GetGenesisUrl() *GenesisURL {
	if x, ok := m.GetSource().(*InitialGenesis_GenesisUrl); ok {
		return x.GenesisUrl
	}
	return nil
}

func (m *InitialGenesis) GetGenesisConfig() *GenesisConfig {
	if x, ok := m.GetSource().(*InitialGenesis_GenesisConfig); ok {
		return x.GenesisConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*InitialGenesis) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*InitialGenesis_DefaultInitialGenesis)(nil),
		(*InitialGenesis_GenesisUrl)(nil),
		(*InitialGenesis_GenesisConfig)(nil),
	}
}

// DefaultInitialGenesis specifies using the default CLI-generated genesis as an
// initial genesis
type DefaultInitialGenesis struct {
}

func (m *DefaultInitialGenesis) Reset()         { *m = DefaultInitialGenesis{} }
func (m *DefaultInitialGenesis) String() string { return proto.CompactTextString(m) }
func (*DefaultInitialGenesis) ProtoMessage()    {}
func (*DefaultInitialGenesis) Descriptor() ([]byte, []int) {
	return fileDescriptor_5649fed3e1144d90, []int{2}
}
func (m *DefaultInitialGenesis) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DefaultInitialGenesis) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DefaultInitialGenesis.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DefaultInitialGenesis) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultInitialGenesis.Merge(m, src)
}
func (m *DefaultInitialGenesis) XXX_Size() int {
	return m.Size()
}
func (m *DefaultInitialGenesis) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultInitialGenesis.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultInitialGenesis proto.InternalMessageInfo

// GenesisURL specifies using a custom genesis from a URL as the initial genesis
type GenesisURL struct {
	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *GenesisURL) Reset()         { *m = GenesisURL{} }
func (m *GenesisURL) String() string { return proto.CompactTextString(m) }
func (*GenesisURL) ProtoMessage()    {}
func (*GenesisURL) Descriptor() ([]byte, []int) {
	return fileDescriptor_5649fed3e1144d90, []int{3}
}
func (m *GenesisURL) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisURL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisURL.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisURL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisURL.Merge(m, src)
}
func (m *GenesisURL) XXX_Size() int {
	return m.Size()
}
func (m *GenesisURL) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisURL.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisURL proto.InternalMessageInfo

func (m *GenesisURL) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GenesisURL) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// GenesisConfig specifies using a custom genesis from a Ignite CLI config file
// the file is located in the root specified by source_url
type GenesisConfig struct {
	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (m *GenesisConfig) Reset()         { *m = GenesisConfig{} }
func (m *GenesisConfig) String() string { return proto.CompactTextString(m) }
func (*GenesisConfig) ProtoMessage()    {}
func (*GenesisConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5649fed3e1144d90, []int{4}
}
func (m *GenesisConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisConfig.Merge(m, src)
}
func (m *GenesisConfig) XXX_Size() int {
	return m.Size()
}
func (m *GenesisConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisConfig proto.InternalMessageInfo

func (m *GenesisConfig) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func init() {
	proto.RegisterType((*Chain)(nil), "network.launch.v1.Chain")
	proto.RegisterType((*InitialGenesis)(nil), "network.launch.v1.InitialGenesis")
	proto.RegisterType((*DefaultInitialGenesis)(nil), "network.launch.v1.DefaultInitialGenesis")
	proto.RegisterType((*GenesisURL)(nil), "network.launch.v1.GenesisURL")
	proto.RegisterType((*GenesisConfig)(nil), "network.launch.v1.GenesisConfig")
}

func init() { proto.RegisterFile("network/launch/v1/chain.proto", fileDescriptor_5649fed3e1144d90) }

var fileDescriptor_5649fed3e1144d90 = []byte{
	// 799 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0xae, 0xdb, 0x44,
	0x14, 0x8e, 0x6f, 0xd2, 0x90, 0x4c, 0x6e, 0x7e, 0x3a, 0xb4, 0xd4, 0x04, 0xdd, 0xc4, 0x04, 0x21,
	0x4c, 0x25, 0x6c, 0x25, 0x6c, 0x58, 0x42, 0x02, 0x22, 0x91, 0x40, 0xaa, 0xac, 0x76, 0xc3, 0xc6,
	0x9a, 0x8c, 0x27, 0xf6, 0x50, 0x7b, 0x26, 0x78, 0xc6, 0x81, 0x3e, 0x03, 0x9b, 0xae, 0x79, 0x02,
	0xc4, 0xaa, 0x1b, 0x24, 0x1e, 0xa1, 0xcb, 0x2e, 0x59, 0xb5, 0xe8, 0xde, 0x45, 0xdf, 0x81, 0x15,
	0x9a, 0x1f, 0xb7, 0x37, 0x10, 0xa4, 0x6e, 0x92, 0xf1, 0xf7, 0x7d, 0xe7, 0xcc, 0x39, 0x3e, 0xe7,
	0x33, 0xb8, 0x60, 0x44, 0xfe, 0xc8, 0xcb, 0x87, 0x61, 0x8e, 0x2a, 0x86, 0xb3, 0xf0, 0x30, 0x0f,
	0x71, 0x86, 0x28, 0x0b, 0xf6, 0x25, 0x97, 0x1c, 0xde, 0xb4, 0x74, 0x60, 0xe8, 0xe0, 0x30, 0x1f,
	0xdf, 0x44, 0x05, 0x65, 0x3c, 0xd4, 0xbf, 0x46, 0x35, 0x9e, 0x60, 0x2e, 0x0a, 0x2e, 0xc2, 0x2d,
	0x12, 0x24, 0x3c, 0xcc, 0xb7, 0x44, 0xa2, 0x79, 0x88, 0x79, 0x9d, 0x65, 0x7c, 0x2b, 0xe5, 0x29,
	0xd7, 0xc7, 0x50, 0x9d, 0x2c, 0x3a, 0x4d, 0x39, 0x4f, 0x73, 0x12, 0xea, 0xa7, 0x6d, 0xb5, 0x0b,
	0x25, 0x2d, 0x88, 0x90, 0xa8, 0xd8, 0x1b, 0xc1, 0xec, 0x8f, 0x36, 0xb8, 0xb1, 0x52, 0xc5, 0xc0,
	0xf7, 0x40, 0xd7, 0x14, 0x10, 0xd3, 0xc4, 0x75, 0x3c, 0xc7, 0x6f, 0x45, 0x1d, 0x03, 0x6c, 0x12,
	0xf8, 0x21, 0x18, 0x60, 0xce, 0xcb, 0x84, 0x32, 0x24, 0x79, 0xa9, 0x14, 0x67, 0x5a, 0xd1, 0xbf,
	0x86, 0x6e, 0x12, 0xe8, 0x83, 0x51, 0x4a, 0x18, 0x11, 0x54, 0xc4, 0xba, 0x43, 0x25, 0x6c, 0x7a,
	0x8e, 0xdf, 0x8d, 0x06, 0x16, 0xd7, 0x77, 0x6d, 0x12, 0x78, 0x01, 0x00, 0x2e, 0x09, 0x92, 0x24,
	0x89, 0x91, 0x74, 0x5b, 0x9e, 0xe3, 0x37, 0xa3, 0xae, 0x45, 0xbe, 0x90, 0x8a, 0x16, 0xbc, 0x2a,
	0x31, 0x89, 0xab, 0x32, 0x77, 0x6f, 0xe8, 0x14, 0x5d, 0x83, 0x3c, 0x28, 0x73, 0x38, 0x05, 0x3d,
	0x4b, 0x67, 0x48, 0x64, 0x6e, 0x5b, 0xf3, 0x36, 0x62, 0x8d, 0x44, 0x06, 0xef, 0x81, 0x21, 0x65,
	0x54, 0x52, 0x94, 0xc7, 0xf6, 0x62, 0xf7, 0x2d, 0xcf, 0xf1, 0x7b, 0x8b, 0xf7, 0x83, 0xff, 0xbc,
	0xed, 0x60, 0x63, 0x94, 0x5f, 0x1b, 0xe1, 0xb2, 0xf5, 0xf4, 0xf9, 0xb4, 0x11, 0x0d, 0xe8, 0x11,
	0xaa, 0xae, 0xcc, 0x90, 0x88, 0xf7, 0x25, 0xff, 0x9e, 0x60, 0xe9, 0x76, 0x3c, 0xc7, 0xef, 0x44,
	0x20, 0x43, 0xe2, 0x9e, 0x41, 0x54, 0xc9, 0x96, 0x54, 0x5d, 0x77, 0xf5, 0xeb, 0xe9, 0x5a, 0xc4,
	0x34, 0x4c, 0x45, 0x5c, 0x20, 0xca, 0x18, 0x91, 0x2e, 0xd0, 0xe1, 0x5d, 0x2a, 0xbe, 0x35, 0x00,
	0xfc, 0x18, 0x8c, 0xec, 0xdb, 0x97, 0x25, 0x4d, 0x53, 0x52, 0x92, 0xc4, 0xed, 0x69, 0xd1, 0xd0,
	0xe0, 0xf7, 0x6b, 0x18, 0x7e, 0x05, 0x7a, 0xb5, 0x94, 0x16, 0xc4, 0x3d, 0xd7, 0x7d, 0x8d, 0x03,
	0x33, 0xe9, 0xa0, 0x9e, 0x74, 0x70, 0xbf, 0x9e, 0xf4, 0xb2, 0xa3, 0x1a, 0x7a, 0xfc, 0x62, 0xea,
	0x44, 0xc0, 0xe6, 0xa2, 0x05, 0x81, 0x9f, 0x01, 0x17, 0x73, 0x26, 0xaa, 0x82, 0x94, 0x71, 0x49,
	0x0e, 0x54, 0x50, 0xce, 0xe2, 0x8c, 0xd0, 0x34, 0x93, 0x6e, 0x5f, 0xcf, 0xe3, 0x9d, 0x9a, 0x8f,
	0x2c, 0xbd, 0xd6, 0x2c, 0x9c, 0x83, 0x5b, 0x05, 0x67, 0x54, 0xf2, 0x92, 0xb2, 0x34, 0xc6, 0x9c,
	0x31, 0x82, 0x25, 0x49, 0xdc, 0x81, 0xae, 0xf7, 0xed, 0xd7, 0xdc, 0xaa, 0xa6, 0xe0, 0xef, 0x0e,
	0x18, 0x22, 0x8c, 0x79, 0xc5, 0x64, 0xbc, 0x45, 0x39, 0x62, 0x98, 0xb8, 0x43, 0xaf, 0xe9, 0xf7,
	0x16, 0xef, 0x06, 0x66, 0xb1, 0x03, 0xb5, 0xd8, 0x81, 0x5d, 0xec, 0x60, 0xc5, 0x29, 0x5b, 0xfe,
	0xa0, 0xea, 0xfe, 0xfb, 0xf9, 0xf4, 0xa3, 0x94, 0xca, 0xac, 0xda, 0x06, 0x98, 0x17, 0xa1, 0x75,
	0x81, 0xf9, 0xfb, 0x44, 0x24, 0x0f, 0x43, 0xf9, 0x68, 0x4f, 0x84, 0x0e, 0xf8, 0xed, 0xc5, 0xd4,
	0x7f, 0x43, 0xa9, 0xf8, 0xe5, 0xe5, 0x93, 0xbb, 0xe7, 0x39, 0x49, 0x11, 0x7e, 0x14, 0x2b, 0x17,
	0x89, 0x5f, 0x5f, 0x3e, 0xb9, 0xeb, 0x44, 0x03, 0x5b, 0xe4, 0xd2, 0xd4, 0x08, 0xc7, 0xa0, 0x53,
	0x10, 0x89, 0x12, 0x24, 0x91, 0x3b, 0xf2, 0x1c, 0xff, 0x3c, 0x7a, 0xf5, 0x3c, 0xfb, 0xf9, 0x0c,
	0x0c, 0x8e, 0x57, 0x07, 0x6e, 0xc1, 0x9d, 0x84, 0xec, 0x50, 0x95, 0xcb, 0xf8, 0xdf, 0xeb, 0xe7,
	0xe8, 0x31, 0xf9, 0x27, 0xd6, 0xef, 0x4b, 0x13, 0x71, 0x9c, 0x6a, 0xdd, 0x88, 0x6e, 0x27, 0xa7,
	0x08, 0xf8, 0x39, 0xe8, 0xd5, 0x1e, 0x53, 0xde, 0x38, 0xd3, 0x79, 0x2f, 0x4e, 0xe4, 0xb5, 0x01,
	0x0f, 0xa2, 0x6f, 0xd6, 0x8d, 0x08, 0xd8, 0x18, 0xe5, 0x9e, 0x0d, 0x18, 0xbc, 0x72, 0x29, 0x67,
	0x3b, 0x9a, 0x6a, 0x8f, 0xf6, 0x16, 0xde, 0xff, 0x27, 0x59, 0x69, 0xdd, 0xba, 0x11, 0xf5, 0xd3,
	0xeb, 0xc0, 0xb2, 0x03, 0xda, 0xc6, 0x75, 0xb3, 0x3b, 0xe0, 0xf6, 0xc9, 0x46, 0x66, 0x0b, 0x00,
	0x5e, 0x57, 0x02, 0x47, 0xa0, 0xa9, 0xaa, 0x76, 0xb4, 0x63, 0xd5, 0x11, 0x42, 0xd0, 0xd2, 0x26,
	0x3e, 0xd3, 0x90, 0x3e, 0xcf, 0x3e, 0x00, 0xfd, 0xa3, 0x8b, 0x95, 0x68, 0x47, 0x73, 0x62, 0xe3,
	0xf4, 0x79, 0xb9, 0x7c, 0x7a, 0x39, 0x71, 0x9e, 0x5d, 0x4e, 0x9c, 0xbf, 0x2e, 0x27, 0xce, 0xe3,
	0xab, 0x49, 0xe3, 0xd9, 0xd5, 0xa4, 0xf1, 0xe7, 0xd5, 0xa4, 0xf1, 0xdd, 0xf5, 0x2d, 0xa0, 0x29,
	0xa3, 0x92, 0x84, 0xf5, 0x27, 0xf8, 0xa7, 0xfa, 0x23, 0xac, 0x77, 0x61, 0xdb, 0xd6, 0x76, 0xf9,
	0xf4, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0xa0, 0xfe, 0xd0, 0xa3, 0x05, 0x00, 0x00,
}

func (m *Chain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Chain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Chain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Metadata) > 0 {
		i -= len(m.Metadata)
		copy(dAtA[i:], m.Metadata)
		i = encodeVarintChain(dAtA, i, uint64(len(m.Metadata)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.AccountBalance) > 0 {
		for iNdEx := len(m.AccountBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccountBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintChain(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x7a
		}
	}
	if m.MonitoringConnected {
		i--
		if m.MonitoringConnected {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if m.ConsumerRevisionHeight != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.ConsumerRevisionHeight))
		i--
		dAtA[i] = 0x68
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.LaunchTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LaunchTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintChain(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x62
	if m.LaunchTriggered {
		i--
		if m.LaunchTriggered {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.IsMainnet {
		i--
		if m.IsMainnet {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.ProjectId != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.ProjectId))
		i--
		dAtA[i] = 0x48
	}
	if m.HasProject {
		i--
		if m.HasProject {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	{
		size, err := m.InitialGenesis.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintChain(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.SourceHash) > 0 {
		i -= len(m.SourceHash)
		copy(dAtA[i:], m.SourceHash)
		i = encodeVarintChain(dAtA, i, uint64(len(m.SourceHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SourceUrl) > 0 {
		i -= len(m.SourceUrl)
		copy(dAtA[i:], m.SourceUrl)
		i = encodeVarintChain(dAtA, i, uint64(len(m.SourceUrl)))
		i--
		dAtA[i] = 0x2a
	}
	if m.CreatedAt != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x20
	}
	if len(m.GenesisChainId) > 0 {
		i -= len(m.GenesisChainId)
		copy(dAtA[i:], m.GenesisChainId)
		i = encodeVarintChain(dAtA, i, uint64(len(m.GenesisChainId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.CoordinatorId != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.CoordinatorId))
		i--
		dAtA[i] = 0x10
	}
	if m.LaunchId != 0 {
		i = encodeVarintChain(dAtA, i, uint64(m.LaunchId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *InitialGenesis) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InitialGenesis) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InitialGenesis) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Source != nil {
		{
			size := m.Source.Size()
			i -= size
			if _, err := m.Source.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *InitialGenesis_DefaultInitialGenesis) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InitialGenesis_DefaultInitialGenesis) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DefaultInitialGenesis != nil {
		{
			size, err := m.DefaultInitialGenesis.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChain(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *InitialGenesis_GenesisUrl) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InitialGenesis_GenesisUrl) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.GenesisUrl != nil {
		{
			size, err := m.GenesisUrl.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChain(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *InitialGenesis_GenesisConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InitialGenesis_GenesisConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.GenesisConfig != nil {
		{
			size, err := m.GenesisConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChain(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *DefaultInitialGenesis) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DefaultInitialGenesis) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DefaultInitialGenesis) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *GenesisURL) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisURL) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisURL) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintChain(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintChain(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.File) > 0 {
		i -= len(m.File)
		copy(dAtA[i:], m.File)
		i = encodeVarintChain(dAtA, i, uint64(len(m.File)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintChain(dAtA []byte, offset int, v uint64) int {
	offset -= sovChain(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Chain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaunchId != 0 {
		n += 1 + sovChain(uint64(m.LaunchId))
	}
	if m.CoordinatorId != 0 {
		n += 1 + sovChain(uint64(m.CoordinatorId))
	}
	l = len(m.GenesisChainId)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovChain(uint64(m.CreatedAt))
	}
	l = len(m.SourceUrl)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	l = len(m.SourceHash)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	l = m.InitialGenesis.Size()
	n += 1 + l + sovChain(uint64(l))
	if m.HasProject {
		n += 2
	}
	if m.ProjectId != 0 {
		n += 1 + sovChain(uint64(m.ProjectId))
	}
	if m.IsMainnet {
		n += 2
	}
	if m.LaunchTriggered {
		n += 2
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.LaunchTime)
	n += 1 + l + sovChain(uint64(l))
	if m.ConsumerRevisionHeight != 0 {
		n += 1 + sovChain(uint64(m.ConsumerRevisionHeight))
	}
	if m.MonitoringConnected {
		n += 2
	}
	if len(m.AccountBalance) > 0 {
		for _, e := range m.AccountBalance {
			l = e.Size()
			n += 1 + l + sovChain(uint64(l))
		}
	}
	l = len(m.Metadata)
	if l > 0 {
		n += 2 + l + sovChain(uint64(l))
	}
	return n
}

func (m *InitialGenesis) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Source != nil {
		n += m.Source.Size()
	}
	return n
}

func (m *InitialGenesis_DefaultInitialGenesis) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DefaultInitialGenesis != nil {
		l = m.DefaultInitialGenesis.Size()
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}
func (m *InitialGenesis_GenesisUrl) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GenesisUrl != nil {
		l = m.GenesisUrl.Size()
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}
func (m *InitialGenesis_GenesisConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GenesisConfig != nil {
		l = m.GenesisConfig.Size()
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}
func (m *DefaultInitialGenesis) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *GenesisURL) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}

func (m *GenesisConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.File)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}

func sovChain(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChain(x uint64) (n int) {
	return sovChain(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Chain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Chain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Chain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchId", wireType)
			}
			m.LaunchId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LaunchId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoordinatorId", wireType)
			}
			m.CoordinatorId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoordinatorId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialGenesis", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialGenesis.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasProject", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HasProject = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectId", wireType)
			}
			m.ProjectId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsMainnet", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsMainnet = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchTriggered", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LaunchTriggered = bool(v != 0)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.LaunchTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerRevisionHeight", wireType)
			}
			m.ConsumerRevisionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsumerRevisionHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonitoringConnected", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MonitoringConnected = bool(v != 0)
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountBalance = append(m.AccountBalance, github_com_cosmos_cosmos_sdk_types.Coin{})
			if err := m.AccountBalance[len(m.AccountBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Metadata = append(m.Metadata[:0], dAtA[iNdEx:postIndex]...)
			if m.Metadata == nil {
				m.Metadata = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InitialGenesis) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InitialGenesis: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InitialGenesis: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultInitialGenesis", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &DefaultInitialGenesis{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Source = &InitialGenesis_DefaultInitialGenesis{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisUrl", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &GenesisURL{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Source = &InitialGenesis_GenesisUrl{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &GenesisConfig{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Source = &InitialGenesis_GenesisConfig{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DefaultInitialGenesis) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DefaultInitialGenesis: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DefaultInitialGenesis: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisURL) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisURL: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisURL: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field File", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChain
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.File = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChain(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChain
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChain
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChain
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChain
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChain        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChain          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChain = fmt.Errorf("proto: unexpected end of group")
)
