// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: network/monitoringp/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19c0c76e95648e0c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19c0c76e95648e0c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetMonitoringInfoRequest struct {
}

func (m *QueryGetMonitoringInfoRequest) Reset()         { *m = QueryGetMonitoringInfoRequest{} }
func (m *QueryGetMonitoringInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMonitoringInfoRequest) ProtoMessage()    {}
func (*QueryGetMonitoringInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19c0c76e95648e0c, []int{2}
}
func (m *QueryGetMonitoringInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMonitoringInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMonitoringInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMonitoringInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMonitoringInfoRequest.Merge(m, src)
}
func (m *QueryGetMonitoringInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMonitoringInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMonitoringInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMonitoringInfoRequest proto.InternalMessageInfo

type QueryGetMonitoringInfoResponse struct {
	MonitoringInfo MonitoringInfo `protobuf:"bytes,1,opt,name=monitoring_info,json=monitoringInfo,proto3" json:"monitoring_info"`
}

func (m *QueryGetMonitoringInfoResponse) Reset()         { *m = QueryGetMonitoringInfoResponse{} }
func (m *QueryGetMonitoringInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMonitoringInfoResponse) ProtoMessage()    {}
func (*QueryGetMonitoringInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19c0c76e95648e0c, []int{3}
}
func (m *QueryGetMonitoringInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMonitoringInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMonitoringInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMonitoringInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMonitoringInfoResponse.Merge(m, src)
}
func (m *QueryGetMonitoringInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMonitoringInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMonitoringInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMonitoringInfoResponse proto.InternalMessageInfo

func (m *QueryGetMonitoringInfoResponse) GetMonitoringInfo() MonitoringInfo {
	if m != nil {
		return m.MonitoringInfo
	}
	return MonitoringInfo{}
}

type QueryGetConnectionChannelIDRequest struct {
}

func (m *QueryGetConnectionChannelIDRequest) Reset()         { *m = QueryGetConnectionChannelIDRequest{} }
func (m *QueryGetConnectionChannelIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetConnectionChannelIDRequest) ProtoMessage()    {}
func (*QueryGetConnectionChannelIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19c0c76e95648e0c, []int{4}
}
func (m *QueryGetConnectionChannelIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetConnectionChannelIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetConnectionChannelIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetConnectionChannelIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetConnectionChannelIDRequest.Merge(m, src)
}
func (m *QueryGetConnectionChannelIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetConnectionChannelIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetConnectionChannelIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetConnectionChannelIDRequest proto.InternalMessageInfo

type QueryGetConnectionChannelIDResponse struct {
	ConnectionChannelId ConnectionChannelID `protobuf:"bytes,1,opt,name=connection_channel_id,json=connectionChannelId,proto3" json:"connection_channel_id"`
}

func (m *QueryGetConnectionChannelIDResponse) Reset()         { *m = QueryGetConnectionChannelIDResponse{} }
func (m *QueryGetConnectionChannelIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetConnectionChannelIDResponse) ProtoMessage()    {}
func (*QueryGetConnectionChannelIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19c0c76e95648e0c, []int{5}
}
func (m *QueryGetConnectionChannelIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetConnectionChannelIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetConnectionChannelIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetConnectionChannelIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetConnectionChannelIDResponse.Merge(m, src)
}
func (m *QueryGetConnectionChannelIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetConnectionChannelIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetConnectionChannelIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetConnectionChannelIDResponse proto.InternalMessageInfo

func (m *QueryGetConnectionChannelIDResponse) GetConnectionChannelId() ConnectionChannelID {
	if m != nil {
		return m.ConnectionChannelId
	}
	return ConnectionChannelID{}
}

type QueryGetConsumerClientIDRequest struct {
}

func (m *QueryGetConsumerClientIDRequest) Reset()         { *m = QueryGetConsumerClientIDRequest{} }
func (m *QueryGetConsumerClientIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetConsumerClientIDRequest) ProtoMessage()    {}
func (*QueryGetConsumerClientIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19c0c76e95648e0c, []int{6}
}
func (m *QueryGetConsumerClientIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetConsumerClientIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetConsumerClientIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetConsumerClientIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetConsumerClientIDRequest.Merge(m, src)
}
func (m *QueryGetConsumerClientIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetConsumerClientIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetConsumerClientIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetConsumerClientIDRequest proto.InternalMessageInfo

type QueryGetConsumerClientIDResponse struct {
	ConsumerClientId ConsumerClientID `protobuf:"bytes,1,opt,name=consumer_client_id,json=consumerClientId,proto3" json:"consumer_client_id"`
}

func (m *QueryGetConsumerClientIDResponse) Reset()         { *m = QueryGetConsumerClientIDResponse{} }
func (m *QueryGetConsumerClientIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetConsumerClientIDResponse) ProtoMessage()    {}
func (*QueryGetConsumerClientIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19c0c76e95648e0c, []int{7}
}
func (m *QueryGetConsumerClientIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetConsumerClientIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetConsumerClientIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetConsumerClientIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetConsumerClientIDResponse.Merge(m, src)
}
func (m *QueryGetConsumerClientIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetConsumerClientIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetConsumerClientIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetConsumerClientIDResponse proto.InternalMessageInfo

func (m *QueryGetConsumerClientIDResponse) GetConsumerClientId() ConsumerClientID {
	if m != nil {
		return m.ConsumerClientId
	}
	return ConsumerClientID{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "network.monitoringp.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "network.monitoringp.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetMonitoringInfoRequest)(nil), "network.monitoringp.v1.QueryGetMonitoringInfoRequest")
	proto.RegisterType((*QueryGetMonitoringInfoResponse)(nil), "network.monitoringp.v1.QueryGetMonitoringInfoResponse")
	proto.RegisterType((*QueryGetConnectionChannelIDRequest)(nil), "network.monitoringp.v1.QueryGetConnectionChannelIDRequest")
	proto.RegisterType((*QueryGetConnectionChannelIDResponse)(nil), "network.monitoringp.v1.QueryGetConnectionChannelIDResponse")
	proto.RegisterType((*QueryGetConsumerClientIDRequest)(nil), "network.monitoringp.v1.QueryGetConsumerClientIDRequest")
	proto.RegisterType((*QueryGetConsumerClientIDResponse)(nil), "network.monitoringp.v1.QueryGetConsumerClientIDResponse")
}

func init() {
	proto.RegisterFile("network/monitoringp/v1/query.proto", fileDescriptor_19c0c76e95648e0c)
}

var fileDescriptor_19c0c76e95648e0c = []byte{
	// 605 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6b, 0x13, 0x4f,
	0x18, 0xc6, 0x33, 0x5f, 0xbe, 0x2d, 0x38, 0x82, 0xda, 0x49, 0x2d, 0xb2, 0xe8, 0xa6, 0x6e, 0xfd,
	0x51, 0x12, 0xb3, 0x63, 0x12, 0xac, 0xbf, 0x4e, 0x26, 0x42, 0xe9, 0x41, 0xd0, 0x80, 0x20, 0x22,
	0x84, 0xcd, 0x66, 0xba, 0x1d, 0xcc, 0xce, 0x6c, 0x77, 0x27, 0xa9, 0xbd, 0x89, 0x67, 0x0f, 0x05,
	0xff, 0x09, 0x8f, 0xde, 0xbc, 0x7a, 0xec, 0xc1, 0x43, 0xc1, 0x8b, 0x27, 0x91, 0x44, 0xf4, 0xdf,
	0x90, 0xcc, 0x4e, 0x9a, 0x6e, 0xb2, 0xb3, 0x6d, 0xbd, 0x84, 0xcd, 0xbb, 0xcf, 0xf3, 0xce, 0xe7,
	0xcd, 0xfb, 0x4c, 0xa0, 0xc5, 0x88, 0xd8, 0xe1, 0xe1, 0x6b, 0xec, 0x73, 0x46, 0x05, 0x0f, 0x29,
	0xf3, 0x02, 0xdc, 0xaf, 0xe0, 0xed, 0x1e, 0x09, 0x77, 0xed, 0x20, 0xe4, 0x82, 0xa3, 0x25, 0xa5,
	0xb1, 0x8f, 0x68, 0xec, 0x7e, 0xc5, 0x58, 0x70, 0x7c, 0xca, 0x38, 0x96, 0x9f, 0xb1, 0xd4, 0x28,
	0xba, 0x3c, 0xf2, 0x79, 0x84, 0xdb, 0x4e, 0x44, 0xe2, 0x1e, 0xb8, 0x5f, 0x69, 0x13, 0xe1, 0x54,
	0x70, 0xe0, 0x78, 0x94, 0x39, 0x82, 0x72, 0xa6, 0xb4, 0x8b, 0x1e, 0xf7, 0xb8, 0x7c, 0xc4, 0xa3,
	0x27, 0x55, 0xbd, 0xec, 0x71, 0xee, 0x75, 0x09, 0x76, 0x02, 0x8a, 0x1d, 0xc6, 0xb8, 0x90, 0x96,
	0x48, 0xbd, 0xad, 0x6a, 0x70, 0x5d, 0xce, 0x18, 0x71, 0x47, 0xca, 0x96, 0xbb, 0xe5, 0x30, 0x46,
	0xba, 0x2d, 0xda, 0x51, 0x1e, 0xac, 0xf7, 0x44, 0x3d, 0x9f, 0x84, 0x2d, 0xb7, 0x4b, 0x09, 0x13,
	0x13, 0xc3, 0x2d, 0x8d, 0x61, 0xf2, 0xb5, 0x45, 0xd9, 0xe6, 0x18, 0x78, 0x45, 0xa3, 0x0e, 0x9c,
	0xd0, 0xf1, 0x15, 0xb7, 0xb5, 0x08, 0xd1, 0xb3, 0xd1, 0xaf, 0xf1, 0x54, 0x16, 0x9b, 0x64, 0xbb,
	0x47, 0x22, 0x61, 0xbd, 0x80, 0xf9, 0x44, 0x35, 0x0a, 0x38, 0x8b, 0x08, 0x7a, 0x04, 0xe7, 0x63,
	0xf3, 0x25, 0xb0, 0x0c, 0x56, 0xcf, 0x56, 0x4d, 0x3b, 0x7d, 0x01, 0x76, 0xec, 0xab, 0x9f, 0xd9,
	0xff, 0x51, 0xc8, 0x7d, 0xfc, 0xf3, 0xa9, 0x08, 0x9a, 0xca, 0x68, 0x15, 0xe0, 0x15, 0xd9, 0x79,
	0x9d, 0x88, 0x27, 0x87, 0x9e, 0x0d, 0xb6, 0xc9, 0xc7, 0x47, 0xef, 0x40, 0x53, 0x27, 0x50, 0x14,
	0xcf, 0xe1, 0xf9, 0xa9, 0x81, 0x15, 0xce, 0x0d, 0x1d, 0x4e, 0xb2, 0x51, 0xfd, 0xff, 0x11, 0x56,
	0xf3, 0x9c, 0x9f, 0xa8, 0x5a, 0xd7, 0xa0, 0x35, 0x3e, 0xb8, 0x71, 0xb8, 0xb4, 0x46, 0xbc, 0xb3,
	0x8d, 0xc7, 0x63, 0xbc, 0xf7, 0x00, 0xae, 0x64, 0xca, 0x14, 0x24, 0x81, 0x17, 0x53, 0x57, 0xaf,
	0x50, 0x4b, 0x3a, 0xd4, 0x94, 0x9e, 0x8a, 0x37, 0xef, 0xce, 0xbc, 0xea, 0x58, 0x57, 0x61, 0xe1,
	0x08, 0x8d, 0x4c, 0x4d, 0x43, 0x86, 0x66, 0x42, 0xfc, 0x16, 0xc0, 0x65, 0xbd, 0x46, 0xe1, 0xbe,
	0x82, 0x68, 0x36, 0x75, 0x8a, 0x75, 0x35, 0x83, 0x35, 0xd1, 0x4d, 0x81, 0x5e, 0x70, 0x93, 0xf5,
	0x4e, 0xf5, 0xf7, 0x1c, 0x9c, 0x93, 0x08, 0x68, 0x0f, 0xc0, 0xf9, 0x38, 0x1c, 0xa8, 0xa8, 0x6b,
	0x3b, 0x9b, 0x47, 0xa3, 0x74, 0x22, 0x6d, 0x3c, 0x8b, 0x55, 0x7e, 0xf7, 0xed, 0xd7, 0x87, 0xff,
	0x6e, 0xa2, 0xeb, 0x98, 0x7a, 0x8c, 0x0a, 0x82, 0x33, 0xef, 0x01, 0xfa, 0x0c, 0xe0, 0xc2, 0x4c,
	0xd8, 0xd0, 0x9d, 0xcc, 0x13, 0x75, 0xe9, 0x35, 0xd6, 0x4e, 0x6b, 0x53, 0xcc, 0x35, 0xc9, 0x5c,
	0x46, 0xa5, 0x2c, 0xe6, 0xa9, 0xd4, 0xa3, 0xaf, 0x00, 0x2e, 0xa5, 0xc7, 0x10, 0x3d, 0x38, 0x8e,
	0x43, 0x1f, 0x71, 0xe3, 0xe1, 0x3f, 0x79, 0xd5, 0x20, 0xf7, 0xe5, 0x20, 0x35, 0x54, 0xc9, 0x1a,
	0x24, 0xf5, 0x66, 0xa0, 0x2f, 0x00, 0xe6, 0x53, 0x32, 0x8a, 0xee, 0x9e, 0x80, 0x27, 0x2d, 0xf9,
	0xc6, 0xbd, 0xd3, 0x1b, 0xd5, 0x14, 0x6b, 0x72, 0x8a, 0xdb, 0xc8, 0x3e, 0x66, 0x8a, 0xa9, 0x0b,
	0x53, 0x5f, 0xdf, 0x1f, 0x98, 0xe0, 0x60, 0x60, 0x82, 0x9f, 0x03, 0x13, 0xec, 0x0d, 0xcd, 0xdc,
	0xc1, 0xd0, 0xcc, 0x7d, 0x1f, 0x9a, 0xb9, 0x97, 0x65, 0x8f, 0x8a, 0xad, 0x5e, 0xdb, 0x76, 0xb9,
	0x3f, 0xdd, 0xf3, 0x4d, 0xa2, 0xab, 0xd8, 0x0d, 0x48, 0xd4, 0x9e, 0x97, 0xff, 0xce, 0xb5, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xfa, 0x6f, 0xa6, 0x06, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a MonitoringInfo by index.
	GetMonitoringInfo(ctx context.Context, in *QueryGetMonitoringInfoRequest, opts ...grpc.CallOption) (*QueryGetMonitoringInfoResponse, error)
	// Queries a ConnectionChannelID by index.
	GetConnectionChannelID(ctx context.Context, in *QueryGetConnectionChannelIDRequest, opts ...grpc.CallOption) (*QueryGetConnectionChannelIDResponse, error)
	// Queries a ConsumerClientID by index.
	GetConsumerClientID(ctx context.Context, in *QueryGetConsumerClientIDRequest, opts ...grpc.CallOption) (*QueryGetConsumerClientIDResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringp.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetMonitoringInfo(ctx context.Context, in *QueryGetMonitoringInfoRequest, opts ...grpc.CallOption) (*QueryGetMonitoringInfoResponse, error) {
	out := new(QueryGetMonitoringInfoResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringp.v1.Query/GetMonitoringInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetConnectionChannelID(ctx context.Context, in *QueryGetConnectionChannelIDRequest, opts ...grpc.CallOption) (*QueryGetConnectionChannelIDResponse, error) {
	out := new(QueryGetConnectionChannelIDResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringp.v1.Query/GetConnectionChannelID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetConsumerClientID(ctx context.Context, in *QueryGetConsumerClientIDRequest, opts ...grpc.CallOption) (*QueryGetConsumerClientIDResponse, error) {
	out := new(QueryGetConsumerClientIDResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringp.v1.Query/GetConsumerClientID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a MonitoringInfo by index.
	GetMonitoringInfo(context.Context, *QueryGetMonitoringInfoRequest) (*QueryGetMonitoringInfoResponse, error)
	// Queries a ConnectionChannelID by index.
	GetConnectionChannelID(context.Context, *QueryGetConnectionChannelIDRequest) (*QueryGetConnectionChannelIDResponse, error)
	// Queries a ConsumerClientID by index.
	GetConsumerClientID(context.Context, *QueryGetConsumerClientIDRequest) (*QueryGetConsumerClientIDResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetMonitoringInfo(ctx context.Context, req *QueryGetMonitoringInfoRequest) (*QueryGetMonitoringInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonitoringInfo not implemented")
}
func (*UnimplementedQueryServer) GetConnectionChannelID(ctx context.Context, req *QueryGetConnectionChannelIDRequest) (*QueryGetConnectionChannelIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnectionChannelID not implemented")
}
func (*UnimplementedQueryServer) GetConsumerClientID(ctx context.Context, req *QueryGetConsumerClientIDRequest) (*QueryGetConsumerClientIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsumerClientID not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringp.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetMonitoringInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMonitoringInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetMonitoringInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringp.v1.Query/GetMonitoringInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetMonitoringInfo(ctx, req.(*QueryGetMonitoringInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetConnectionChannelID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetConnectionChannelIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetConnectionChannelID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringp.v1.Query/GetConnectionChannelID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetConnectionChannelID(ctx, req.(*QueryGetConnectionChannelIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetConsumerClientID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetConsumerClientIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetConsumerClientID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringp.v1.Query/GetConsumerClientID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetConsumerClientID(ctx, req.(*QueryGetConsumerClientIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "network.monitoringp.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetMonitoringInfo",
			Handler:    _Query_GetMonitoringInfo_Handler,
		},
		{
			MethodName: "GetConnectionChannelID",
			Handler:    _Query_GetConnectionChannelID_Handler,
		},
		{
			MethodName: "GetConsumerClientID",
			Handler:    _Query_GetConsumerClientID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network/monitoringp/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetMonitoringInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMonitoringInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMonitoringInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetMonitoringInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMonitoringInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMonitoringInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MonitoringInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetConnectionChannelIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetConnectionChannelIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetConnectionChannelIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetConnectionChannelIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetConnectionChannelIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetConnectionChannelIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ConnectionChannelId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetConsumerClientIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetConsumerClientIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetConsumerClientIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetConsumerClientIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetConsumerClientIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetConsumerClientIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ConsumerClientId.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetMonitoringInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetMonitoringInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MonitoringInfo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetConnectionChannelIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetConnectionChannelIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ConnectionChannelId.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetConsumerClientIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetConsumerClientIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ConsumerClientId.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMonitoringInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMonitoringInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMonitoringInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMonitoringInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMonitoringInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMonitoringInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonitoringInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MonitoringInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetConnectionChannelIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetConnectionChannelIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetConnectionChannelIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetConnectionChannelIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetConnectionChannelIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetConnectionChannelIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionChannelId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ConnectionChannelId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetConsumerClientIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetConsumerClientIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetConsumerClientIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetConsumerClientIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetConsumerClientIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetConsumerClientIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerClientId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ConsumerClientId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
