// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: network/monitoringc/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetLaunchIDFromChannelIDRequest struct {
	ChannelID string `protobuf:"bytes,1,opt,name=channelID,proto3" json:"channelID,omitempty"`
}

func (m *QueryGetLaunchIDFromChannelIDRequest) Reset()         { *m = QueryGetLaunchIDFromChannelIDRequest{} }
func (m *QueryGetLaunchIDFromChannelIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLaunchIDFromChannelIDRequest) ProtoMessage()    {}
func (*QueryGetLaunchIDFromChannelIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{2}
}
func (m *QueryGetLaunchIDFromChannelIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLaunchIDFromChannelIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLaunchIDFromChannelIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLaunchIDFromChannelIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLaunchIDFromChannelIDRequest.Merge(m, src)
}
func (m *QueryGetLaunchIDFromChannelIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLaunchIDFromChannelIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLaunchIDFromChannelIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLaunchIDFromChannelIDRequest proto.InternalMessageInfo

func (m *QueryGetLaunchIDFromChannelIDRequest) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

type QueryGetLaunchIDFromChannelIDResponse struct {
	LaunchIDFromChannelID LaunchIDFromChannelID `protobuf:"bytes,1,opt,name=launchIDFromChannelID,proto3" json:"launchIDFromChannelID"`
}

func (m *QueryGetLaunchIDFromChannelIDResponse) Reset()         { *m = QueryGetLaunchIDFromChannelIDResponse{} }
func (m *QueryGetLaunchIDFromChannelIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLaunchIDFromChannelIDResponse) ProtoMessage()    {}
func (*QueryGetLaunchIDFromChannelIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{3}
}
func (m *QueryGetLaunchIDFromChannelIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLaunchIDFromChannelIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLaunchIDFromChannelIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLaunchIDFromChannelIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLaunchIDFromChannelIDResponse.Merge(m, src)
}
func (m *QueryGetLaunchIDFromChannelIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLaunchIDFromChannelIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLaunchIDFromChannelIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLaunchIDFromChannelIDResponse proto.InternalMessageInfo

func (m *QueryGetLaunchIDFromChannelIDResponse) GetLaunchIDFromChannelID() LaunchIDFromChannelID {
	if m != nil {
		return m.LaunchIDFromChannelID
	}
	return LaunchIDFromChannelID{}
}

type QueryAllLaunchIDFromChannelIDRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLaunchIDFromChannelIDRequest) Reset()         { *m = QueryAllLaunchIDFromChannelIDRequest{} }
func (m *QueryAllLaunchIDFromChannelIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllLaunchIDFromChannelIDRequest) ProtoMessage()    {}
func (*QueryAllLaunchIDFromChannelIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{4}
}
func (m *QueryAllLaunchIDFromChannelIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLaunchIDFromChannelIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLaunchIDFromChannelIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLaunchIDFromChannelIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLaunchIDFromChannelIDRequest.Merge(m, src)
}
func (m *QueryAllLaunchIDFromChannelIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLaunchIDFromChannelIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLaunchIDFromChannelIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLaunchIDFromChannelIDRequest proto.InternalMessageInfo

func (m *QueryAllLaunchIDFromChannelIDRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllLaunchIDFromChannelIDResponse struct {
	LaunchIDFromChannelID []LaunchIDFromChannelID `protobuf:"bytes,1,rep,name=launchIDFromChannelID,proto3" json:"launchIDFromChannelID"`
	Pagination            *query.PageResponse     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLaunchIDFromChannelIDResponse) Reset()         { *m = QueryAllLaunchIDFromChannelIDResponse{} }
func (m *QueryAllLaunchIDFromChannelIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllLaunchIDFromChannelIDResponse) ProtoMessage()    {}
func (*QueryAllLaunchIDFromChannelIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{5}
}
func (m *QueryAllLaunchIDFromChannelIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLaunchIDFromChannelIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLaunchIDFromChannelIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLaunchIDFromChannelIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLaunchIDFromChannelIDResponse.Merge(m, src)
}
func (m *QueryAllLaunchIDFromChannelIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLaunchIDFromChannelIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLaunchIDFromChannelIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLaunchIDFromChannelIDResponse proto.InternalMessageInfo

func (m *QueryAllLaunchIDFromChannelIDResponse) GetLaunchIDFromChannelID() []LaunchIDFromChannelID {
	if m != nil {
		return m.LaunchIDFromChannelID
	}
	return nil
}

func (m *QueryAllLaunchIDFromChannelIDResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetMonitoringHistoryRequest struct {
	LaunchID uint64 `protobuf:"varint,1,opt,name=launchID,proto3" json:"launchID,omitempty"`
}

func (m *QueryGetMonitoringHistoryRequest) Reset()         { *m = QueryGetMonitoringHistoryRequest{} }
func (m *QueryGetMonitoringHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMonitoringHistoryRequest) ProtoMessage()    {}
func (*QueryGetMonitoringHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{6}
}
func (m *QueryGetMonitoringHistoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMonitoringHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMonitoringHistoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMonitoringHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMonitoringHistoryRequest.Merge(m, src)
}
func (m *QueryGetMonitoringHistoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMonitoringHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMonitoringHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMonitoringHistoryRequest proto.InternalMessageInfo

func (m *QueryGetMonitoringHistoryRequest) GetLaunchID() uint64 {
	if m != nil {
		return m.LaunchID
	}
	return 0
}

type QueryGetMonitoringHistoryResponse struct {
	MonitoringHistory MonitoringHistory `protobuf:"bytes,1,opt,name=monitoringHistory,proto3" json:"monitoringHistory"`
}

func (m *QueryGetMonitoringHistoryResponse) Reset()         { *m = QueryGetMonitoringHistoryResponse{} }
func (m *QueryGetMonitoringHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMonitoringHistoryResponse) ProtoMessage()    {}
func (*QueryGetMonitoringHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{7}
}
func (m *QueryGetMonitoringHistoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMonitoringHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMonitoringHistoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMonitoringHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMonitoringHistoryResponse.Merge(m, src)
}
func (m *QueryGetMonitoringHistoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMonitoringHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMonitoringHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMonitoringHistoryResponse proto.InternalMessageInfo

func (m *QueryGetMonitoringHistoryResponse) GetMonitoringHistory() MonitoringHistory {
	if m != nil {
		return m.MonitoringHistory
	}
	return MonitoringHistory{}
}

type QueryGetVerifiedClientIDRequest struct {
	LaunchID uint64 `protobuf:"varint,1,opt,name=launchID,proto3" json:"launchID,omitempty"`
}

func (m *QueryGetVerifiedClientIDRequest) Reset()         { *m = QueryGetVerifiedClientIDRequest{} }
func (m *QueryGetVerifiedClientIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetVerifiedClientIDRequest) ProtoMessage()    {}
func (*QueryGetVerifiedClientIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{8}
}
func (m *QueryGetVerifiedClientIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVerifiedClientIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVerifiedClientIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVerifiedClientIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVerifiedClientIDRequest.Merge(m, src)
}
func (m *QueryGetVerifiedClientIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVerifiedClientIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVerifiedClientIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVerifiedClientIDRequest proto.InternalMessageInfo

func (m *QueryGetVerifiedClientIDRequest) GetLaunchID() uint64 {
	if m != nil {
		return m.LaunchID
	}
	return 0
}

type QueryGetVerifiedClientIDResponse struct {
	VerifiedClientID VerifiedClientID `protobuf:"bytes,1,opt,name=verifiedClientID,proto3" json:"verifiedClientID"`
}

func (m *QueryGetVerifiedClientIDResponse) Reset()         { *m = QueryGetVerifiedClientIDResponse{} }
func (m *QueryGetVerifiedClientIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetVerifiedClientIDResponse) ProtoMessage()    {}
func (*QueryGetVerifiedClientIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{9}
}
func (m *QueryGetVerifiedClientIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetVerifiedClientIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetVerifiedClientIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetVerifiedClientIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetVerifiedClientIDResponse.Merge(m, src)
}
func (m *QueryGetVerifiedClientIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetVerifiedClientIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetVerifiedClientIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetVerifiedClientIDResponse proto.InternalMessageInfo

func (m *QueryGetVerifiedClientIDResponse) GetVerifiedClientID() VerifiedClientID {
	if m != nil {
		return m.VerifiedClientID
	}
	return VerifiedClientID{}
}

type QueryGetProviderClientIDRequest struct {
	LaunchID uint64 `protobuf:"varint,1,opt,name=launchID,proto3" json:"launchID,omitempty"`
}

func (m *QueryGetProviderClientIDRequest) Reset()         { *m = QueryGetProviderClientIDRequest{} }
func (m *QueryGetProviderClientIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetProviderClientIDRequest) ProtoMessage()    {}
func (*QueryGetProviderClientIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{10}
}
func (m *QueryGetProviderClientIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetProviderClientIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetProviderClientIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetProviderClientIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetProviderClientIDRequest.Merge(m, src)
}
func (m *QueryGetProviderClientIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetProviderClientIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetProviderClientIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetProviderClientIDRequest proto.InternalMessageInfo

func (m *QueryGetProviderClientIDRequest) GetLaunchID() uint64 {
	if m != nil {
		return m.LaunchID
	}
	return 0
}

type QueryGetProviderClientIDResponse struct {
	ProviderClientID ProviderClientID `protobuf:"bytes,1,opt,name=providerClientID,proto3" json:"providerClientID"`
}

func (m *QueryGetProviderClientIDResponse) Reset()         { *m = QueryGetProviderClientIDResponse{} }
func (m *QueryGetProviderClientIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetProviderClientIDResponse) ProtoMessage()    {}
func (*QueryGetProviderClientIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{11}
}
func (m *QueryGetProviderClientIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetProviderClientIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetProviderClientIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetProviderClientIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetProviderClientIDResponse.Merge(m, src)
}
func (m *QueryGetProviderClientIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetProviderClientIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetProviderClientIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetProviderClientIDResponse proto.InternalMessageInfo

func (m *QueryGetProviderClientIDResponse) GetProviderClientID() ProviderClientID {
	if m != nil {
		return m.ProviderClientID
	}
	return ProviderClientID{}
}

type QueryAllProviderClientIDRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllProviderClientIDRequest) Reset()         { *m = QueryAllProviderClientIDRequest{} }
func (m *QueryAllProviderClientIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllProviderClientIDRequest) ProtoMessage()    {}
func (*QueryAllProviderClientIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{12}
}
func (m *QueryAllProviderClientIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllProviderClientIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllProviderClientIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllProviderClientIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllProviderClientIDRequest.Merge(m, src)
}
func (m *QueryAllProviderClientIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllProviderClientIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllProviderClientIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllProviderClientIDRequest proto.InternalMessageInfo

func (m *QueryAllProviderClientIDRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllProviderClientIDResponse struct {
	ProviderClientID []ProviderClientID  `protobuf:"bytes,1,rep,name=providerClientID,proto3" json:"providerClientID"`
	Pagination       *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllProviderClientIDResponse) Reset()         { *m = QueryAllProviderClientIDResponse{} }
func (m *QueryAllProviderClientIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllProviderClientIDResponse) ProtoMessage()    {}
func (*QueryAllProviderClientIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82561013049aca62, []int{13}
}
func (m *QueryAllProviderClientIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllProviderClientIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllProviderClientIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllProviderClientIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllProviderClientIDResponse.Merge(m, src)
}
func (m *QueryAllProviderClientIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllProviderClientIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllProviderClientIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllProviderClientIDResponse proto.InternalMessageInfo

func (m *QueryAllProviderClientIDResponse) GetProviderClientID() []ProviderClientID {
	if m != nil {
		return m.ProviderClientID
	}
	return nil
}

func (m *QueryAllProviderClientIDResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "network.monitoringc.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "network.monitoringc.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetLaunchIDFromChannelIDRequest)(nil), "network.monitoringc.v1.QueryGetLaunchIDFromChannelIDRequest")
	proto.RegisterType((*QueryGetLaunchIDFromChannelIDResponse)(nil), "network.monitoringc.v1.QueryGetLaunchIDFromChannelIDResponse")
	proto.RegisterType((*QueryAllLaunchIDFromChannelIDRequest)(nil), "network.monitoringc.v1.QueryAllLaunchIDFromChannelIDRequest")
	proto.RegisterType((*QueryAllLaunchIDFromChannelIDResponse)(nil), "network.monitoringc.v1.QueryAllLaunchIDFromChannelIDResponse")
	proto.RegisterType((*QueryGetMonitoringHistoryRequest)(nil), "network.monitoringc.v1.QueryGetMonitoringHistoryRequest")
	proto.RegisterType((*QueryGetMonitoringHistoryResponse)(nil), "network.monitoringc.v1.QueryGetMonitoringHistoryResponse")
	proto.RegisterType((*QueryGetVerifiedClientIDRequest)(nil), "network.monitoringc.v1.QueryGetVerifiedClientIDRequest")
	proto.RegisterType((*QueryGetVerifiedClientIDResponse)(nil), "network.monitoringc.v1.QueryGetVerifiedClientIDResponse")
	proto.RegisterType((*QueryGetProviderClientIDRequest)(nil), "network.monitoringc.v1.QueryGetProviderClientIDRequest")
	proto.RegisterType((*QueryGetProviderClientIDResponse)(nil), "network.monitoringc.v1.QueryGetProviderClientIDResponse")
	proto.RegisterType((*QueryAllProviderClientIDRequest)(nil), "network.monitoringc.v1.QueryAllProviderClientIDRequest")
	proto.RegisterType((*QueryAllProviderClientIDResponse)(nil), "network.monitoringc.v1.QueryAllProviderClientIDResponse")
}

func init() {
	proto.RegisterFile("network/monitoringc/v1/query.proto", fileDescriptor_82561013049aca62)
}

var fileDescriptor_82561013049aca62 = []byte{
	// 848 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xdf, 0x6b, 0xd3, 0x5c,
	0x18, 0xc7, 0x9b, 0x6d, 0xef, 0x78, 0x77, 0x76, 0xf3, 0xee, 0xac, 0xaf, 0xcc, 0x30, 0xba, 0x19,
	0x9d, 0x9b, 0x93, 0x25, 0x76, 0xe2, 0x7e, 0xa0, 0x13, 0xba, 0x8d, 0xcd, 0xc1, 0x84, 0xd9, 0x0b,
	0x91, 0x81, 0x94, 0xb4, 0x3d, 0x4b, 0x0f, 0x26, 0x39, 0x59, 0x92, 0x56, 0xc7, 0x98, 0x17, 0xbb,
	0xf4, 0x6a, 0xe8, 0x3f, 0xe1, 0xa5, 0xff, 0x82, 0x57, 0x0e, 0x04, 0x19, 0x78, 0xa1, 0x20, 0x88,
	0x74, 0x82, 0xff, 0x86, 0xf4, 0xe4, 0x64, 0x6d, 0x93, 0x9c, 0x64, 0x2d, 0xbd, 0x29, 0x4d, 0xce,
	0x79, 0xbe, 0xe7, 0xfb, 0x79, 0x72, 0xce, 0xf3, 0x1c, 0x20, 0x99, 0xc8, 0x7d, 0x49, 0xec, 0x17,
	0x8a, 0x41, 0x4c, 0xec, 0x12, 0x1b, 0x9b, 0x5a, 0x49, 0xa9, 0x65, 0x95, 0xfd, 0x2a, 0xb2, 0x0f,
	0x64, 0xcb, 0x26, 0x2e, 0x81, 0x57, 0xd8, 0x1c, 0xb9, 0x65, 0x8e, 0x5c, 0xcb, 0x8a, 0x23, 0xaa,
	0x81, 0x4d, 0xa2, 0xd0, 0x5f, 0x6f, 0xaa, 0x38, 0x5b, 0x22, 0x8e, 0x41, 0x1c, 0xa5, 0xa8, 0x3a,
	0xc8, 0xd3, 0x50, 0x6a, 0xd9, 0x22, 0x72, 0xd5, 0xac, 0x62, 0xa9, 0x1a, 0x36, 0x55, 0x17, 0x13,
	0x93, 0xcd, 0x4d, 0x6b, 0x44, 0x23, 0xf4, 0xaf, 0xd2, 0xf8, 0xc7, 0xde, 0x8e, 0x6b, 0x84, 0x68,
	0x3a, 0x52, 0x54, 0x0b, 0x2b, 0xaa, 0x69, 0x12, 0x97, 0x86, 0x38, 0x6c, 0x74, 0x81, 0x63, 0x57,
	0x57, 0xab, 0x66, 0xa9, 0x52, 0xc0, 0xe5, 0xc2, 0x9e, 0x4d, 0x8c, 0x42, 0xa9, 0xa2, 0x9a, 0x26,
	0xd2, 0x0b, 0xb8, 0xcc, 0xe2, 0x14, 0x4e, 0x5c, 0xf3, 0xb1, 0x50, 0xc1, 0x8e, 0x4b, 0x7c, 0x66,
	0xf1, 0x3a, 0x27, 0xc0, 0x52, 0x6d, 0xd5, 0x70, 0x12, 0x54, 0x2d, 0x9b, 0xd4, 0x70, 0x19, 0xd9,
	0x85, 0x92, 0x8e, 0x91, 0xe9, 0x26, 0xdb, 0xa8, 0x21, 0x1b, 0xef, 0x61, 0x54, 0x0e, 0x06, 0x48,
	0x69, 0x00, 0x9f, 0x34, 0xb2, 0xb8, 0x43, 0x97, 0xcd, 0xa3, 0xfd, 0x2a, 0x72, 0x5c, 0xe9, 0x19,
	0x18, 0x6d, 0x7b, 0xeb, 0x58, 0xc4, 0x74, 0x10, 0xcc, 0x81, 0x41, 0xcf, 0xde, 0x98, 0x30, 0x29,
	0xcc, 0x0c, 0xcf, 0x67, 0xe4, 0xe8, 0x0f, 0x27, 0x7b, 0x71, 0xab, 0x43, 0xa7, 0x3f, 0x27, 0x52,
	0xef, 0xff, 0x7c, 0x98, 0x15, 0xf2, 0x2c, 0x50, 0x5a, 0x07, 0x37, 0xa8, 0xf2, 0x26, 0x72, 0xb7,
	0x69, 0x4a, 0xb7, 0xd6, 0x37, 0x6c, 0x62, 0xac, 0x79, 0xf9, 0xdc, 0x5a, 0x67, 0x0e, 0xe0, 0x38,
	0x18, 0x2a, 0xf9, 0xef, 0xe8, 0x6a, 0x43, 0xf9, 0xe6, 0x0b, 0xe9, 0xad, 0x00, 0xa6, 0x12, 0x64,
	0x98, 0x65, 0x0c, 0xfe, 0xd7, 0xa3, 0x26, 0x30, 0x82, 0x39, 0x1e, 0x41, 0xa4, 0xea, 0xea, 0x40,
	0x03, 0x28, 0x1f, 0xad, 0x28, 0x99, 0x0c, 0x2d, 0xa7, 0xeb, 0xb1, 0x68, 0x1b, 0x00, 0x34, 0xb7,
	0x2a, 0xf3, 0x71, 0x53, 0xf6, 0xf6, 0xb5, 0xdc, 0xd8, 0xd7, 0xb2, 0x77, 0x36, 0xd8, 0xbe, 0x96,
	0x77, 0x54, 0x0d, 0xb1, 0xd8, 0x7c, 0x4b, 0xa4, 0xf4, 0xc3, 0x4f, 0x02, 0x7f, 0xc1, 0xe4, 0x24,
	0xf4, 0xf7, 0x36, 0x09, 0x70, 0xb3, 0x0d, 0xae, 0x8f, 0xc2, 0x4d, 0x27, 0xc2, 0x79, 0x3e, 0xdb,
	0xe8, 0x1e, 0x82, 0x49, 0xff, 0x0b, 0x3f, 0xbe, 0x70, 0xf5, 0xc8, 0x3b, 0x42, 0x7e, 0x26, 0x45,
	0xf0, 0xaf, 0xef, 0x82, 0xe6, 0x71, 0x20, 0x7f, 0xf1, 0x2c, 0x1d, 0x0b, 0xe0, 0x5a, 0x8c, 0x00,
	0xcb, 0xcc, 0x73, 0x30, 0x62, 0x04, 0x07, 0xd9, 0x27, 0xb9, 0xc5, 0xcb, 0x4a, 0x48, 0x8d, 0x65,
	0x24, 0xac, 0x24, 0xad, 0x80, 0x09, 0xdf, 0xc3, 0x53, 0x76, 0x02, 0xd7, 0xe8, 0x01, 0x6c, 0xee,
	0x86, 0x38, 0x86, 0xd7, 0xcd, 0x1c, 0x84, 0xc3, 0x19, 0xc1, 0x2e, 0xf8, 0xaf, 0x16, 0x18, 0x63,
	0x00, 0x33, 0x3c, 0x80, 0xa0, 0x16, 0xf3, 0x1f, 0xd2, 0x69, 0xb5, 0xbf, 0xc3, 0x2a, 0x4e, 0x97,
	0xf6, 0xc3, 0xe1, 0x4d, 0xfb, 0x56, 0x60, 0x2c, 0xc9, 0x7e, 0x50, 0xcb, 0xb7, 0x1f, 0xd4, 0x91,
	0x30, 0xb3, 0x9f, 0xd3, 0x75, 0x9e, 0xfd, 0x5e, 0x9d, 0xc5, 0x4f, 0x02, 0x63, 0x8d, 0x5c, 0x2b,
	0x96, 0xb5, 0xbf, 0x17, 0xac, 0x3d, 0x3b, 0x77, 0xf3, 0x6f, 0x86, 0xc1, 0x3f, 0x94, 0x04, 0x9e,
	0x08, 0x60, 0xd0, 0x2b, 0xe4, 0x70, 0x96, 0xe7, 0x2f, 0xdc, 0x3b, 0xc4, 0xdb, 0x97, 0x9a, 0xeb,
	0xad, 0x2c, 0xcd, 0x1d, 0x7f, 0xfd, 0xfd, 0xae, 0x6f, 0x1a, 0x4e, 0x29, 0x58, 0x33, 0xb1, 0x8b,
	0x94, 0xd8, 0xae, 0x08, 0xeb, 0x02, 0x18, 0xe3, 0x95, 0x7c, 0xf8, 0x20, 0x76, 0xe1, 0x84, 0x86,
	0x23, 0xae, 0x74, 0x19, 0xcd, 0x40, 0xb6, 0x28, 0xc8, 0x1a, 0xcc, 0xc5, 0x81, 0x70, 0x2f, 0x11,
	0xca, 0xe1, 0x45, 0x6f, 0x3b, 0x82, 0xdf, 0x04, 0x70, 0x75, 0x1b, 0x3b, 0x5d, 0x51, 0x26, 0xf4,
	0x9e, 0x04, 0xca, 0xa4, 0x46, 0x22, 0xad, 0x50, 0xca, 0x45, 0x78, 0xaf, 0x2b, 0x4a, 0xf8, 0x45,
	0x00, 0xe9, 0xa8, 0x72, 0x0c, 0x97, 0x92, 0x92, 0xcf, 0x6b, 0x01, 0xe2, 0x72, 0x17, 0x91, 0x0c,
	0x26, 0x47, 0x61, 0xee, 0xc3, 0xe5, 0x38, 0x98, 0xf0, 0xfd, 0x4d, 0x39, 0xf4, 0x0b, 0xdc, 0x11,
	0xfc, 0x2c, 0x80, 0xd1, 0x88, 0xe2, 0x0c, 0x17, 0x93, 0x5c, 0x71, 0xba, 0x81, 0xb8, 0xd4, 0x79,
	0x60, 0x27, 0x34, 0xe1, 0x6b, 0x60, 0x04, 0x4d, 0xb0, 0xe6, 0x24, 0xd3, 0x70, 0xaa, 0x6b, 0x32,
	0x0d, 0xaf, 0x54, 0x5e, 0x8e, 0x26, 0x7c, 0x0b, 0x6e, 0xa5, 0xf9, 0x28, 0x80, 0x74, 0xe3, 0x18,
	0x75, 0x88, 0xc3, 0x6f, 0x16, 0x09, 0x38, 0x31, 0x95, 0x5f, 0x5a, 0xa0, 0x38, 0x77, 0xa0, 0xdc,
	0x19, 0xce, 0xea, 0xe6, 0x69, 0x3d, 0x23, 0x9c, 0xd5, 0x33, 0xc2, 0xaf, 0x7a, 0x46, 0x38, 0x39,
	0xcf, 0xa4, 0xce, 0xce, 0x33, 0xa9, 0xef, 0xe7, 0x99, 0xd4, 0xee, 0x9c, 0x86, 0xdd, 0x4a, 0xb5,
	0x28, 0x97, 0x88, 0x11, 0xd4, 0x7c, 0xd5, 0xa6, 0xea, 0x1e, 0x58, 0xc8, 0x29, 0x0e, 0xd2, 0xdb,
	0xfe, 0xdd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x25, 0xf8, 0xaa, 0x0c, 0x8e, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of LaunchIDFromChannelID items.
	GetLaunchIDFromChannelID(ctx context.Context, in *QueryGetLaunchIDFromChannelIDRequest, opts ...grpc.CallOption) (*QueryGetLaunchIDFromChannelIDResponse, error)
	ListLaunchIDFromChannelID(ctx context.Context, in *QueryAllLaunchIDFromChannelIDRequest, opts ...grpc.CallOption) (*QueryAllLaunchIDFromChannelIDResponse, error)
	// Queries a list of MonitoringHistory items.
	GetMonitoringHistory(ctx context.Context, in *QueryGetMonitoringHistoryRequest, opts ...grpc.CallOption) (*QueryGetMonitoringHistoryResponse, error)
	// Queries a list of VerifiedClientID items.
	GetVerifiedClientID(ctx context.Context, in *QueryGetVerifiedClientIDRequest, opts ...grpc.CallOption) (*QueryGetVerifiedClientIDResponse, error)
	// Queries a list of ProviderClientID items.
	GetProviderClientID(ctx context.Context, in *QueryGetProviderClientIDRequest, opts ...grpc.CallOption) (*QueryGetProviderClientIDResponse, error)
	ListProviderClientID(ctx context.Context, in *QueryAllProviderClientIDRequest, opts ...grpc.CallOption) (*QueryAllProviderClientIDResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringc.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetLaunchIDFromChannelID(ctx context.Context, in *QueryGetLaunchIDFromChannelIDRequest, opts ...grpc.CallOption) (*QueryGetLaunchIDFromChannelIDResponse, error) {
	out := new(QueryGetLaunchIDFromChannelIDResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringc.v1.Query/GetLaunchIDFromChannelID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListLaunchIDFromChannelID(ctx context.Context, in *QueryAllLaunchIDFromChannelIDRequest, opts ...grpc.CallOption) (*QueryAllLaunchIDFromChannelIDResponse, error) {
	out := new(QueryAllLaunchIDFromChannelIDResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringc.v1.Query/ListLaunchIDFromChannelID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetMonitoringHistory(ctx context.Context, in *QueryGetMonitoringHistoryRequest, opts ...grpc.CallOption) (*QueryGetMonitoringHistoryResponse, error) {
	out := new(QueryGetMonitoringHistoryResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringc.v1.Query/GetMonitoringHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetVerifiedClientID(ctx context.Context, in *QueryGetVerifiedClientIDRequest, opts ...grpc.CallOption) (*QueryGetVerifiedClientIDResponse, error) {
	out := new(QueryGetVerifiedClientIDResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringc.v1.Query/GetVerifiedClientID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProviderClientID(ctx context.Context, in *QueryGetProviderClientIDRequest, opts ...grpc.CallOption) (*QueryGetProviderClientIDResponse, error) {
	out := new(QueryGetProviderClientIDResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringc.v1.Query/GetProviderClientID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListProviderClientID(ctx context.Context, in *QueryAllProviderClientIDRequest, opts ...grpc.CallOption) (*QueryAllProviderClientIDResponse, error) {
	out := new(QueryAllProviderClientIDResponse)
	err := c.cc.Invoke(ctx, "/network.monitoringc.v1.Query/ListProviderClientID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of LaunchIDFromChannelID items.
	GetLaunchIDFromChannelID(context.Context, *QueryGetLaunchIDFromChannelIDRequest) (*QueryGetLaunchIDFromChannelIDResponse, error)
	ListLaunchIDFromChannelID(context.Context, *QueryAllLaunchIDFromChannelIDRequest) (*QueryAllLaunchIDFromChannelIDResponse, error)
	// Queries a list of MonitoringHistory items.
	GetMonitoringHistory(context.Context, *QueryGetMonitoringHistoryRequest) (*QueryGetMonitoringHistoryResponse, error)
	// Queries a list of VerifiedClientID items.
	GetVerifiedClientID(context.Context, *QueryGetVerifiedClientIDRequest) (*QueryGetVerifiedClientIDResponse, error)
	// Queries a list of ProviderClientID items.
	GetProviderClientID(context.Context, *QueryGetProviderClientIDRequest) (*QueryGetProviderClientIDResponse, error)
	ListProviderClientID(context.Context, *QueryAllProviderClientIDRequest) (*QueryAllProviderClientIDResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetLaunchIDFromChannelID(ctx context.Context, req *QueryGetLaunchIDFromChannelIDRequest) (*QueryGetLaunchIDFromChannelIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLaunchIDFromChannelID not implemented")
}
func (*UnimplementedQueryServer) ListLaunchIDFromChannelID(ctx context.Context, req *QueryAllLaunchIDFromChannelIDRequest) (*QueryAllLaunchIDFromChannelIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLaunchIDFromChannelID not implemented")
}
func (*UnimplementedQueryServer) GetMonitoringHistory(ctx context.Context, req *QueryGetMonitoringHistoryRequest) (*QueryGetMonitoringHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonitoringHistory not implemented")
}
func (*UnimplementedQueryServer) GetVerifiedClientID(ctx context.Context, req *QueryGetVerifiedClientIDRequest) (*QueryGetVerifiedClientIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerifiedClientID not implemented")
}
func (*UnimplementedQueryServer) GetProviderClientID(ctx context.Context, req *QueryGetProviderClientIDRequest) (*QueryGetProviderClientIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderClientID not implemented")
}
func (*UnimplementedQueryServer) ListProviderClientID(ctx context.Context, req *QueryAllProviderClientIDRequest) (*QueryAllProviderClientIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviderClientID not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringc.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetLaunchIDFromChannelID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLaunchIDFromChannelIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetLaunchIDFromChannelID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringc.v1.Query/GetLaunchIDFromChannelID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetLaunchIDFromChannelID(ctx, req.(*QueryGetLaunchIDFromChannelIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListLaunchIDFromChannelID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllLaunchIDFromChannelIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListLaunchIDFromChannelID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringc.v1.Query/ListLaunchIDFromChannelID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListLaunchIDFromChannelID(ctx, req.(*QueryAllLaunchIDFromChannelIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetMonitoringHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMonitoringHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetMonitoringHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringc.v1.Query/GetMonitoringHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetMonitoringHistory(ctx, req.(*QueryGetMonitoringHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetVerifiedClientID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetVerifiedClientIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVerifiedClientID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringc.v1.Query/GetVerifiedClientID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVerifiedClientID(ctx, req.(*QueryGetVerifiedClientIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProviderClientID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetProviderClientIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProviderClientID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringc.v1.Query/GetProviderClientID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProviderClientID(ctx, req.(*QueryGetProviderClientIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListProviderClientID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllProviderClientIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListProviderClientID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.monitoringc.v1.Query/ListProviderClientID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListProviderClientID(ctx, req.(*QueryAllProviderClientIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "network.monitoringc.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetLaunchIDFromChannelID",
			Handler:    _Query_GetLaunchIDFromChannelID_Handler,
		},
		{
			MethodName: "ListLaunchIDFromChannelID",
			Handler:    _Query_ListLaunchIDFromChannelID_Handler,
		},
		{
			MethodName: "GetMonitoringHistory",
			Handler:    _Query_GetMonitoringHistory_Handler,
		},
		{
			MethodName: "GetVerifiedClientID",
			Handler:    _Query_GetVerifiedClientID_Handler,
		},
		{
			MethodName: "GetProviderClientID",
			Handler:    _Query_GetProviderClientID_Handler,
		},
		{
			MethodName: "ListProviderClientID",
			Handler:    _Query_ListProviderClientID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network/monitoringc/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLaunchIDFromChannelIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLaunchIDFromChannelIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLaunchIDFromChannelIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChannelID) > 0 {
		i -= len(m.ChannelID)
		copy(dAtA[i:], m.ChannelID)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ChannelID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLaunchIDFromChannelIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLaunchIDFromChannelIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLaunchIDFromChannelIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LaunchIDFromChannelID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllLaunchIDFromChannelIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLaunchIDFromChannelIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLaunchIDFromChannelIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllLaunchIDFromChannelIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLaunchIDFromChannelIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLaunchIDFromChannelIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.LaunchIDFromChannelID) > 0 {
		for iNdEx := len(m.LaunchIDFromChannelID) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LaunchIDFromChannelID[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMonitoringHistoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMonitoringHistoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMonitoringHistoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LaunchID != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LaunchID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMonitoringHistoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMonitoringHistoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMonitoringHistoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.MonitoringHistory.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetVerifiedClientIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVerifiedClientIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVerifiedClientIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LaunchID != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LaunchID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetVerifiedClientIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetVerifiedClientIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetVerifiedClientIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.VerifiedClientID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetProviderClientIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetProviderClientIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetProviderClientIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LaunchID != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LaunchID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetProviderClientIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetProviderClientIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetProviderClientIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ProviderClientID.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllProviderClientIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllProviderClientIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllProviderClientIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllProviderClientIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllProviderClientIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllProviderClientIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ProviderClientID) > 0 {
		for iNdEx := len(m.ProviderClientID) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProviderClientID[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLaunchIDFromChannelIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChannelID)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetLaunchIDFromChannelIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LaunchIDFromChannelID.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllLaunchIDFromChannelIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllLaunchIDFromChannelIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LaunchIDFromChannelID) > 0 {
		for _, e := range m.LaunchIDFromChannelID {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetMonitoringHistoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaunchID != 0 {
		n += 1 + sovQuery(uint64(m.LaunchID))
	}
	return n
}

func (m *QueryGetMonitoringHistoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MonitoringHistory.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetVerifiedClientIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaunchID != 0 {
		n += 1 + sovQuery(uint64(m.LaunchID))
	}
	return n
}

func (m *QueryGetVerifiedClientIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VerifiedClientID.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetProviderClientIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LaunchID != 0 {
		n += 1 + sovQuery(uint64(m.LaunchID))
	}
	return n
}

func (m *QueryGetProviderClientIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ProviderClientID.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllProviderClientIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllProviderClientIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ProviderClientID) > 0 {
		for _, e := range m.ProviderClientID {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLaunchIDFromChannelIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLaunchIDFromChannelIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLaunchIDFromChannelIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLaunchIDFromChannelIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLaunchIDFromChannelIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLaunchIDFromChannelIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchIDFromChannelID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LaunchIDFromChannelID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLaunchIDFromChannelIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLaunchIDFromChannelIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLaunchIDFromChannelIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLaunchIDFromChannelIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLaunchIDFromChannelIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLaunchIDFromChannelIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchIDFromChannelID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LaunchIDFromChannelID = append(m.LaunchIDFromChannelID, LaunchIDFromChannelID{})
			if err := m.LaunchIDFromChannelID[len(m.LaunchIDFromChannelID)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMonitoringHistoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMonitoringHistoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMonitoringHistoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchID", wireType)
			}
			m.LaunchID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LaunchID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMonitoringHistoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMonitoringHistoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMonitoringHistoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MonitoringHistory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MonitoringHistory.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVerifiedClientIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVerifiedClientIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVerifiedClientIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchID", wireType)
			}
			m.LaunchID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LaunchID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetVerifiedClientIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetVerifiedClientIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetVerifiedClientIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifiedClientID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VerifiedClientID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetProviderClientIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetProviderClientIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetProviderClientIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LaunchID", wireType)
			}
			m.LaunchID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LaunchID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetProviderClientIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetProviderClientIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetProviderClientIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderClientID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProviderClientID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllProviderClientIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllProviderClientIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllProviderClientIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllProviderClientIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllProviderClientIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllProviderClientIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderClientID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderClientID = append(m.ProviderClientID, ProviderClientID{})
			if err := m.ProviderClientID[len(m.ProviderClientID)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
